--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: django-service 
spec: 
  selector:
    app:
      django-app 

  ports:
    - protocol: "TCP"
      port: 80 
      targetPort: 8000 
  type: LoadBalancer 

--- 

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: django-app-deployment 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: django-app 
  template: 
    metadata: 
      labels:
        app: django-app 
    spec: 
      containers: 
        - name: django 
          image: lucasqz/kubernetes1:latest
          ports:
            - containerPort: 8000